# Generated by Django 5.0.7 on 2024-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('jsonData', models.JSONField()),
            ],
        ),
    ]
